### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Mattkins** [Techie-Qabila/fastify-mongoose#5]
Trying to remediate vulnerabilities and I see the 3 pull requests. @mahmed8003 if you need some help or someone to take this project over, I'd be happy to do it.

**Comment by mahmed8003** [comment]
@Mattkins thanks for reaching out. I am busy these days, but I sent you invitation. It would be great if you take care of those pull requests.

**Comment by Mattkins** [comment]
Happy to help!
